common_js:
    inputs:
        - %kernel.root_dir%/../web/bundles/avanzuadmintheme/vendor/jquery/dist/jquery.js
        - %kernel.root_dir%/../web/bundles/avanzuadmintheme/vendor/jquery-ui/ui/jquery-ui.js
